name: Daily EMA Screener

on:
  schedule:
    - cron: '30 14 * * 1-5'  # 6:30 AM PST Mon-Fri
    - cron: '30 15 * * 1-5'  # 7:30 AM PST
    - cron: '30 16 * * 1-5'  # 8:30 AM PST
    - cron: '30 17 * * 1-5'  # 9:30 AM PST
    - cron: '30 18 * * 1-5'  # 10:30 AM PST
    - cron: '30 19 * * 1-5'  # 11:30 AM PST
    - cron: '30 20 * * 1-5'  # 12:30 PM PST
    - cron: '0 21 * * 1-5'   # 1:00 PM PST
  workflow_dispatch:

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install yfinance requests
      - name: Run EMA Screener
        run: python screener.py
